### ISSUE TITLE
Broken CI

### ISSUE THREAD

**Issue by loic-yvonnet** [loic-yvonnet/algo-appliquee#108]
The GitHub Action named **Build Marp Slide deck** breaks due to the following unhandled exception:

```bash
(node:1859) UnhandledPromiseRejectionWarning: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /home/runner/work/algo-appliquee/algo-appliquee/node_modules/katex/package.json
    at applyExports (internal/modules/cjs/loader.js:491:9)
    at resolveExports (internal/modules/cjs/loader.js:507:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:635:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (/home/runner/work/algo-appliquee/algo-appliquee/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/runner/work/algo-appliquee/algo-appliquee/node_modules/@marp-team/marp-core/lib/marp.js:1:520)
    at Module._compile (/home/runner/work/algo-appliquee/algo-appliquee/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
```

This log may be found in some of the latest [log messages](https://github.com/loic-yvonnet/algo-appliquee/runs/4954035328?check_suite_focus=true).

Compiling locally the website works fine and the above exception is not thrown.

The problem does not come from the CI operating system: it works fine locally on Ubuntu 18.04 LTS, but it fails in GitHub Actions Docker with Ubuntu 18.04 LTS as well (verified in an alternate branch).

The problem might come from the `npm` version. The version used locally is **8.1.3**, whereas the `npm` version used by the CI is older: **6.14.5**.

A suggestion was to add the following snippet to `package.json`:

```json
    "exports": {
        "./package.json": "./package.json"
    }
```

This suggestion does not help in this case.

[Some other suggestion](https://stackoverflow.com/questions/62246824/error-err-package-path-not-exported-no-exports-main-resolved-in-app-node-m) involves the addition of the `@babel/helper-compilation-targets` dependency, but it does not help either in this case.

Since the compilation of the slide decks fails silently, the CI ends with a success code. The sad part is that it means that the CI silently deploys the website without the slide decks.

To avoid breaking again the website:

- it was manually compiled locally,
- the CI has been deleted until a proper solution is found.

**Comment by loic-yvonnet** [comment]
Fixed thanks to:

* Latest dependencies
* Best practices from [Automate6500](https://github.com/automate6500/04-03-github-pages/tree/main).
* Workflow from [Marp CLI Example](https://github.com/yhatt/marp-cli-example/blob/master/.github/workflows/github-pages.yml)
